version: "3"
services:
  web:
    container_name: web
    build: .
    ports:
      - "5000:80"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/mlhfinalproject
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - web

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
          
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

volumes:
  nginx_secrets:
  mydatabase:
