name: Docker build

on:
  push:
    branches:
      - main

jobs:
  buildx:
    name: Run Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
        # Setup Docker Build X
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build
        run: |
          docker build .